config/routes.rb
Rails.application.routes.draw do
  root :to => 'companies#index'

  resources :companies do
    resources :jobs
  end
  resources :jobs, only: [:index]

  resources :categories

  resources :comments, only: [:create]

  resources :contacts, only: [:create]

  get 'dashboard', to: 'dashboard#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true, uniqueness: true
  has_many :jobs, dependent: :destroy
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true
  belongs_to :job
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, :city, presence: true
  validates :name, uniqueness: true
  has_many :jobs
  has_many :contacts
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :full_name, presence: true
  validates :position, presence: true
  validates :email, presence: true
  validates :company_id, presence: true
  belongs_to :company

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, :level_of_interest, presence: true
  belongs_to :company
  belongs_to :category
  has_many :comments
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @category = Category.all
  end
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      redirect_to categories_path
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    @category.update(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render :index
    end
  end
  private

  def category_params
    params.require(:category).permit(:title)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    job = Job.find(params[:job][:id])
    company = job.company
    @comment = Comment.new(comments_params)
    @comment.job_id = job.id
    if @comment.save
      redirect_to company_job_path(company, job)
    else
      render :new
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def index
      @company = Company.where(city: params[:location])
      @companies = Company.all.order(:city)
      @jobs = Company.where(city: params[:location])
      if params.include?("sort")
        render :location
      elsif params.keys.include?("location")
        render :city
      else
        render :index
      end
    end

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:success] = "#{@company.name} added!"
      redirect_to company_path(@company)
    else
      render :new
    end
  end

  def show
    company = Company.find(params[:id])
    redirect_to company_jobs_path(company)
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    if @company.save
      flash[:success] = "#{@company.name} updated!"
      redirect_to company_path(@company)
    else
      render :edit
    end
  end

  def destroy
    company = Company.find(params[:id])
    company.delete

    flash[:success] = "#{company.name} was successfully deleted!"
    redirect_to companies_path
  end


  private

  def company_params
    params.require(:company).permit(:name, :city)
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def create
    @contact = Contact.new(contact_params)
    @contact.company_id = params[:company_id]
    @contact.save
    redirect_to company_jobs_path(@contact.company)
    end

  private


  def contact_params
    params.require(:contact).permit(:full_name, :position, :email, :company_id)
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @jobs = Job.order(:level_of_interest).reverse
    @companies = Company.all
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
      @contacts = Contact.all
      @contact = Contact.new
      @company = Company.find(params[:company_id])
      @jobs = @company.jobs
  end

  def new
    @categories = Category.all
    @company = Company.find(params[:company_id])
    @job = Job.new()
  end

  def create
    @categories = Category.all
    @company = Company.find(params[:company_id])
    @job = @company.jobs.new(job_params)
    if @job.save
      flash[:success] = "You created #{@job.title} at #{@company.name}"
      redirect_to company_job_path(@company, @job)
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @job = Job.find(params[:id])
  end

  def edit
    @categories = Category.all
    @company = Company.find(params[:company_id])
    @job = Job.find(params[:id])
  end

  def update
    @company = Company.find(params[:company_id])
    @job = Job.find(params[:id])
    if Job.update(params[:id], job_params)
      redirect_to company_job_path(@company, @job)
    else
      render :edit
    end
  end

  def destroy
    job = Job.find(params[:id])
    job.delete
    redirect_to company_jobs_path
  end

  private

  def job_params
    params.require(:job).permit(:title, :description, :level_of_interest, :category_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/categories/edit.html.erb
<h1>Update Category Here</h1>

<%= form_for @category do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit %>
<% end %>

app/views/categories/index.html.erb
<h1> Available Job Categories</h1>

<% @category.each do |category| %>
  <ul class="category_">
    <%= link_to category.title, category_path(category) %> <%= link_to "Delete", category_path(category), method: :delete, data: { confirm: "Are you sure you want to delete this category?" } %> <%= link_to "Edit", edit_category_path(category) %>
  </ul>
<% end %>
<%= link_to "Create New", new_category_url %>

app/views/categories/new.html.erb
<h1>Create a new Category</h1>
<%= form_for @category do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.submit  %>
<% end %>

app/views/categories/show.html.erb
<h1><%= @category.title %></h1>

<ul>
  <% @category.jobs.each do |job| %>
    <li><%= link_to job.title, company_path(job.company) %></li>
  <% end %>
<%= link_to "Create New", new_category_url %>
<%= link_to "Categories Index", categories_path %>

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :city %>
  <%= f.text_field :city %>

  <%= f.submit %>
<% end %>

app/views/companies/city.html.erb
<h1>Jobs in <%= @jobs.first.city %></h1>


<% @jobs.each do |job| %>
  <% job.jobs.each do |job| %>
    <li> <%= link_to job.title, company_job_path(@company, job.id) %> </li>
    <% end %>
  <% end  %>

app/views/companies/edit.html.erb
<h2>Edit <%= @company.name %> here!</h2>

<%= render partial: "form" %>

app/views/companies/index.html.erb
<h3>All Companies</h3>

<% @companies.each do |company| %>
  <ul class=company_<%= company.id %>>
    <%= link_to company.name, company_path(company) %> - <%= company.city %><br>
    <%= link_to "Edit", edit_company_path(company) %>
    <%= link_to "Delete", company_path(company), method: "delete" %>
  </ul>
<% end %>

app/views/companies/location.html.erb
<h1>Companies and Jobs by City</h1>

<ol>
<% @companies.each do |company| %>
<li><%= company.name %>: <%= company.city %></li>
<% company.jobs.each do |job| %>
  <%= job.title %></br>
  <% end  %>
<% end %>
</ol>

app/views/companies/new.html.erb
<h2>Create a new company here!</h2>

<%= render partial: "form" %>

app/views/companies/show.html.erb
All Jobs for <strong><%= @company.name %></strong>

<% @company.jobs.each do |job| %>
  <ul><%= job.title %></ul>
<% end %>

app/views/dashboard/index.html.erb
<h1>Your Dashboard</h1>

<% @jobs.each do |job| %>
  <ol><%= job.title %> <%= job.level_of_interest %></ol>
<% end %>

<h1>Top Three Companies by Level of Interest</h1>
<% @companies.each do |company| %>
  <ol><%= company.name %> <%= company.jobs.average(:level_of_interest).round(1) %></ol>
<% end %>

app/views/jobs/_form.html.erb
<%= form_for [@company, @job] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :level_of_interest %>
  <%= f.number_field :level_of_interest %>

  <%= f.label :category %>
  <%= f.collection_select :category_id, @categories,:id,:title, include_black: true %>

  <%= f.submit %>
<% end %>

app/views/jobs/edit.html.erb
<h2>Edit <%= @job.title %> here!</h2>

<%= render partial: "form" %>

app/views/jobs/index.html.erb
All Jobs for <strong><%= @company.name %></strong>

<% @jobs.each do |job| %>
  <ul><%= link_to job.title, company_job_path(@company, job.id) %> at <%= job.company.name %></ul>
<% end %>
<%= link_to "Companies Index", companies_path %>

<h3>Enter Contact</h3>
<%= form_for @contact do |f| %>
  <%= f.label :name %>
  <%= f.text_field :full_name %>

  <%= f.label :position %>
  <%= f.text_field :position %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= hidden_field_tag :company_id, @company.id %>

  <%= f.submit %>
<% end %>


<% @company.contacts.each do |contact| %>
  <p><%= contact.full_name %>, <%= contact.position %>, <%= contact.email %></p>
<% end %>

app/views/jobs/new.html.erb
<h2>Create a new job at <%= @company.name %> here!</h2>

<%= render partial: "form" %>

app/views/jobs/show.html.erb
Title: <%= @job.title %>
<br>

Description: <%= @job.description %>
<br>

Level of Interest: <%= @job.level_of_interest %>
<br>

Company: <%= link_to @job.company.name, company_path(@job.company) %>
<br>

<%= link_to "Edit", edit_company_job_path %>
<%= link_to "Delete", company_job_path, method: :delete %>
<%= link_to "Jobs Index", company_jobs_path %>
<h3>Comments</h3>
<%= form_for @comment do |f| %>
  <%= f.label :comment %>
  <%= f.text_field :content %>
  <%= hidden_field(:job, :id) %>

  <%= f.submit %>
<% end %>

<ol><% @job.comments.reverse_order.each do |comment| %>
  <li><%= comment.content %></li>
  <p>Posted <%= distance_of_time_in_words(comment.job.created_at, comment.created_at) %> later</p>
<% end %></ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>JobTracker</title>
  <link href="css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
    <%= content_tag :div, msg, class: name %>
  <% end %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="js/bootstrap.min.js"></script>
<%= yield %>

</body>
</html>